[system]
compatible=Buildroot EFI Boot Guard RAUC Demo
bootloader=efibootguard
data-directory=/var/lib/rauc
bundle-formats=-plain

[keyring]
path=/etc/rauc/rauc-bundle.cert.pem

[slot.system.a]
device=/dev/disk/by-partlabel/system-a
type=ext4
bootname=0

[slot.system.b]
device=/dev/disk/by-partlabel/system-b
type=ext4
bootname=1
