#!/bin/sh
# Generates a raw disk image with an ESP containing the EFI Boot Guard
# bootloader binary, two EFI Boot Guard slot config partitions and two
# filesystem partitions. This allows for "A/B" booting.
#
# The first slot is populated with the filesystem generated by the Buildroot
# build and the second slot is an empty placeholder.
#
# With SIGN_BINARIES=1, the bootloader and kernel artifacts are signed with
# user-generated keys. Otherwise, the artifacts are installed unsigned.
#
# With UKI=1, EFI Boot Guard is configured to boot a Unified Kernel Image
# (kernel & command line bundled into one binary) which is suitable for secure
# boot. Otherwise, EFI Boot Guard will boot the kernel & command line specified
# in the slot config.
set -e

BOARD_DIR="$(dirname "$0")"

# Kernel command line parameters.
# The rootfs is mounted using a hard-coded partlabel for simplicity.
# This will need to be modified when generating images for other slots.
KERNEL_CMDLINE="root=PARTLABEL=system-a"

# Hardware watchdog timeout, in seconds, armed by EFI Boot Guard before it
# boots the kernel. Set to 0 to disable arming the watchdog.
WATCHDOG_TIMEOUT=120

# Kernel image format.
# Set to 1 to build a Unified Kernel Image (kernel & command line bundled into
# one PE binary).
# Set to 0 to use the raw kernel image instead.
UKI=1

# Sign EFI Boot Guard binary and kernel artifact.
# Set to 1 to sign the artifacts; 0 to disable signing.
SIGN_BINARIES=1

# Staging directory for the EFI System Partition contents.
EFI_DIR="${BINARIES_DIR}/efi-part"

# Persistent location for the user's UEFI Secure Boot keys.
KEYS_DIR="${BINARIES_DIR}/secure-boot-keys"

# Sign a PE/EFI binary with the db key.
sign_pe() {
	input="$1"
	output="$2"
	"${HOST_DIR}/bin/osslsigncode" sign -h sha256 \
		-key "${KEYS_DIR}/db.key" \
		-certs "${KEYS_DIR}/db.crt" \
		-in "$input" \
		-out "$output"
}

# Generate EFI Boot Guard slot configuration.
generate_slot_config() {
	slot_dir="$1"
	label="$2"
	revision="$3"
	ustate="$4"
	kernel="$5"
	args="${KERNEL_CMDLINE}"

	# When booting a UKI, EFI Boot Guard ignores the kernel command line set in
	# the slot config and instead reads the command line embedded in the UKI.
	# If the slot config has non-empty args entry, EFI Boot Guard warns during
	# boot. So if we are building a UKI, generate the slot config with an empty
	# args parameter.
	if [ "${UKI}" -eq 1 ]; then
		args=""
	fi

	mkdir -p "${slot_dir}"
	printf "%s" "${label}" | iconv -f ascii -t UTF-16LE > "${slot_dir}/EFILABEL"

	"${HOST_DIR}/bin/bg_setenv" \
		--verbose \
		--watchdog="${WATCHDOG_TIMEOUT}" \
		--filepath="${slot_dir}/BGENV.DAT" \
		--revision="${revision}" \
		--ustate="${ustate}" \
		--kernel="${kernel}" \
		--args="${args}"
}

# Reset staging directories.
rm -rf \
	"${EFI_DIR}" \
	"${BINARIES_DIR}/boot-a-part" \
	"${BINARIES_DIR}/boot-b-part"
mkdir -p \
	"${EFI_DIR}/EFI/BOOT" \
	"${BINARIES_DIR}/boot-a-part" \
	"${BINARIES_DIR}/boot-b-part"

# If signing is enabled, sign the EFI Boot Guard binary and install it into the
# ESP. Otherwise install the unsigned binary into the ESP.
if [ "${SIGN_BINARIES}" -eq 1 ]; then
	# Ensure the Secure Boot keys exist.
	# These must be generated by the user beforehand; see the readme for
	# instructions.
	for key in db.key db.crt PK.cer KEK.cer db.cer; do
		if [ ! -f "${KEYS_DIR}/${key}" ]; then
			echo "ERROR: Secure Boot key '${KEYS_DIR}/${key}' not found." >&2
			echo "Generate the Secure Boot keys before building; see the readme." >&2
			exit 1
		fi
	done

	# Sign the EFI Boot Guard bootloader and install it into the ESP.
	sign_pe "${BINARIES_DIR}/efibootguardx64.efi" \
		"${EFI_DIR}/EFI/BOOT/BOOTX64.EFI"

	# Copy the certificates into the ESP to allow users to enrol them into UEFI
	# firmware.
	mkdir -p "${EFI_DIR}/keys"
	cp "${KEYS_DIR}/PK.cer" "${KEYS_DIR}/KEK.cer" "${KEYS_DIR}/db.cer" \
		"${EFI_DIR}/keys/"
else
	# If unsigned, just install the bootloader binary into the ESP.
	install -m 0644 "${BINARIES_DIR}/efibootguardx64.efi" \
		"${EFI_DIR}/EFI/BOOT/BOOTX64.EFI"
fi

# Build a Unified Kernel Image (bundling the EFI Boot Guard stub, raw kernel and
# command line).
if [ "${UKI}" -eq 1 ]; then
	"${HOST_DIR}/bin/bg_gen_unified_kernel" \
		"${BINARIES_DIR}/kernel-stubx64.efi" \
		"${BINARIES_DIR}/bzImage" \
		"${BINARIES_DIR}/kernel-uki.efi" \
		--cmdline "${KERNEL_CMDLINE}"

	KERNEL_IMAGE="kernel-uki.efi"
else
	# If not building a UKI, use the raw kernel image.
	KERNEL_IMAGE="bzImage"
fi

# Copy the kernel image into boot-a (optionally signing the image).
if [ "${SIGN_BINARIES}" -eq 1 ]; then
	sign_pe "${BINARIES_DIR}/${KERNEL_IMAGE}" "${BINARIES_DIR}/boot-a-part/${KERNEL_IMAGE}"
else
	cp "${BINARIES_DIR}/${KERNEL_IMAGE}" "${BINARIES_DIR}/boot-a-part/${KERNEL_IMAGE}"
fi

# Generate the EFI Boot Guard slot configuration.
# Set boot-a ustate=OK, the path to the kernel binary and (optionally; if not
# booting a UKI) the kernel command line parameter.
generate_slot_config \
	"${BINARIES_DIR}/boot-a-part" \
	"boot-a" "2" "OK" \
	"C:boot-a:${KERNEL_IMAGE}"

# Set boot-b ustate=FAILED so EFI Boot Guard doesn't boot it.
generate_slot_config \
	"${BINARIES_DIR}/boot-b-part" \
	"boot-b" "1" "FAILED" ""

# Generate the disk image.
support/scripts/genimage.sh -c "${BOARD_DIR}/genimage.cfg"
